### ISSUE TITLE
Unable to build in Windows 8.1

### ISSUE THREAD

**Issue by PapaMufflon** [fsharp/FAKE#764]
Just cloned this repo and run build.cmd. This is my current output:
```
Build FAILED.                                                                                                                                                                                         
                                                                                                                                                                                                      
         C:\Users\tobiaswalter\src\FAKE\src\test\FsCheck.Fake\FsCheck.Fake.fsproj(59,3): warning MSB4011: "C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\Microsoft.FSharp.Targets" cann 
       ot be imported again. It was already imported at "C:\Users\tobiaswalter\src\FAKE\src\test\FsCheck.Fake\FsCheck.Fake.fsproj (51,3)". This is most likely a build authoring error. This subseque 
       nt import will be ignored.                                                                                                                                                                     
                                                                                                                                                                                                      
                                                                                                                                                                                                      
       "C:\Users\tobiaswalter\src\FAKE\FAKE.sln" (Build target) (1) ->                                                                                                                                
       "C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FakeLib.fsproj" (default target) (4) ->                                                                                                        
       (ResolveAssemblyReferences target) ->                                                                                                                                                          
         C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "FSharp.Compiler.S 
       ervice". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FakeLib.f 
       sproj]                                                                                                                                                                                         
         C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3243: No way to resolve conflict between "Microsoft.Web.XmlTransform, Version=2.1.0.0, C 
       ulture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "Microsoft.Web.XmlTransform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null". Choosing "Microsoft.Web.XmlTransform, Version=2.1.0. 
       0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily. [C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FakeLib.fsproj]                                                              
                                                                                                                                                                                                      
                                                                                                                                                                                                      
       "C:\Users\tobiaswalter\src\FAKE\FAKE.sln" (Build target) (1) ->                                                                                                                                
       "C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FakeLib.fsproj" (default target) (4) ->                                                                                                        
       (CoreCompile target) ->                                                                                                                                                                        
         C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\DynamicsNavHelper.fs(443,7): warning FS0026: This rule will never be matched [C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FakeLib.fsproj]  
         C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\DynamicsNavHelper.fs(454,7): warning FS0026: This rule will never be matched [C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FakeLib.fsproj]  
                                                                                                                                                                                                      
                                                                                                                                                                                                      
       "C:\Users\tobiaswalter\src\FAKE\FAKE.sln" (Build target) (1) ->                                                                                                                                
       "C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FakeLib.fsproj" (default target) (4) ->                                                                                                        
       (CoreCompile target) ->                                                                                                                                                                        
         C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FSIHelper.fs(88,23): error FS0039: The namespace 'Compiler' is not defined [C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FakeLib.fsproj]    
         C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FSIHelper.fs(101,21): error FS0039: The namespace or module 'FsiEvaluationSession' is not defined [C:\Users\tobiaswalter\src\FAKE\src\app\Fak 
       eLib\FakeLib.fsproj]                                                                                                                                                                           
         C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FSIHelper.fs(122,23): error FS0039: The namespace or module 'FsiEvaluationSession' is not defined [C:\Users\tobiaswalter\src\FAKE\src\app\Fak 
       eLib\FakeLib.fsproj]                                                                                                                                                                           
         C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FSIHelper.fs(125,13): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotatio 
       n may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FakeLib.fsproj]     
         C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FscHelper.fs(5,23): error FS0039: The namespace 'Compiler' is not defined [C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FakeLib.fsproj]     
         C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FscHelper.fs(50,15): error FS0039: The value or constructor 'SimpleSourceCodeServices' is not defined [C:\Users\tobiaswalter\src\FAKE\src\app 
       \FakeLib\FakeLib.fsproj]                                                                                                                                                                       
         C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FscHelper.fs(66,28): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation 
        may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FakeLib.fsproj]      
         C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FscHelper.fs(71,15): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation 
        may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FakeLib.fsproj]      
         C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FscHelper.fs(72,28): error FS0039: The constructor, module or namespace 'Compiler' is not defined [C:\Users\tobiaswalter\src\FAKE\src\app\Fak 
       eLib\FakeLib.fsproj]                                                                                                                                                                           
                                                                                                                                                                                                      
    5 Warning(s)                                                                                                                                                                                      
    9 Error(s)                                                                                                                                                                                        
```

What am I missing? (Windows 8.1 with VS 2013 installed)

**Comment by PapaMufflon** [comment]
Ok, it's getting scarier: I can run the script from http://fsharp.github.io/FAKE/gettingstarted.html without problems. But when I run the Fake/build.cmd (and it fails), I am no longer able to run the getting-started-script. It gives me this:
```
Package "FAKE" is already installed.
Building project with version: LocalBuild
The following targets are available:
   Clean
   BuildApp
   Default
Target ""Default"" is not defined. Existing targets:
  - Clean
  - BuildApp
  - Default

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
No target was successfully completed
---------------------------------------------------------------------

F# Interactive for F# 3.1 (private)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> [Loading C:\Users\tobiaswalter\src\Demo\buildscripts\build.fsx]

System.Exception: Target ""Default"" is not defined.
   at Fake.TargetHelper.getTarget@72-2.Invoke(String message) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 72
   at Fake.TargetHelper.runTarget@431(String targetName) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 433
   at Fake.TargetHelper.run$cont@429(String targetName, Unit unitVar) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 463
   at Fake.TargetHelper.run(String targetName) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 429
   at Fake.AdditionalSyntax.RunTargetOrDefault(String defaultTarget) in C:\code\fake\src\app\FakeLib\AdditionalSyntax.fs:line 29
   at <StartupCode$FSI_0001>.$FSI_0001_Build$fsx.main@() in C:\Users\tobiaswalter\src\Demo\buildscripts\build.fsx:line 26
Stopped due to error

Press any key to continue . . .
```
When I restart my computer, I am able to sucessfully run the getting-started-script again. I must do something completely wrong!?

**Comment by matthid** [comment]
> System.Exception: Target ""Default"" is not defined.

I have seen this before on the windows `cmd.exe`. Sometimes windows `cmd.exe` is just in some non working state (after running some builds).

Usually to get it running I use `build.cmd Default` instead of `build.cmd` (specifying the target explicitly), but I have no idea what or why that is. Possibly some Environment variable thing?

I think most of the people use the `git bash` and run `./build.sh` (which happens to work)

**Comment by PapaMufflon** [comment]
It works neither with `cmd.exe` nor with `cmder` with `build.cmd` or `build.cmd Default`.
Also, I installed `mono` and tried the build with `git bash` and `./build.sh` with no success (same result).

This is a company computer - maybe there are some weird environment variables set or something like that. That's it, no FAKE PR for me :(

**Comment by forki** [comment]
Hi, 

this is strange. The current master should build on Windows 8.1 - I have it here too. 

The very first error looks like F# is not installed or at least a strange F# version gets referenced. 

If you open the solution, then does the fscheck project compile?

**Comment by PapaMufflon** [comment]
@forki if you mean FsCheck.Fake, then no, it does not compile in Visual Studio.

**Comment by forki** [comment]
yeah. so it looks like a more general problem and might affect more than the FAKE source base.

**Comment by PapaMufflon** [comment]
Ok, I blame my company for messing up F# when setting up the computer. As long as FAKE runs from the NuGet package, I'm happy :)

**Comment by matthid** [comment]
> "C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FakeLib.fsproj" (default target) (4) 
-> (ResolveAssemblyReferences target) 
-> C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "FSharp.Compiler.Service". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\tobiaswalter\src\FAKE\src\app\FakeLib\FakeLib.fsproj]

Have you tried deleting the `/packages/FSharp.Compiler.Service` folder (or everything with `git clean -xdf`) and running `build.cmd` again? It looks like FSharp.Compiler.Service was not downloaded properly. In any case: The complete build log might be helpful (from a clean build, if this is reproducible, not your current state).

> I installed mono and tried the build with git bash and ./build.sh with no success (same result).

Sorry my bad, normally this works without mono on ProjectScaffold like projects, it seems like FAKE's `build.sh` was never updated (see https://github.com/fsharp/FAKE/pull/772).

**Comment by dsyme** [comment]
Closing old issue
