### ISSUE TITLE
 Mono: error FS0039: The value or constructor 'RestoreMSSolutionPackages' is not defined

### ISSUE THREAD

**Issue by Aaronontheweb** [fsharp/FAKE#839]
Running the [FAKE file included as part of Akka.NET's toolchain](https://github.com/akkadotnet/akka.net/blob/dev/build.fsx) and I immediately run into the following issue when attempting to build on Mono (Ubuntu 14.04 LTS) using the target "all"

> /home/azureuser/temp/akka.net/build.fsx(65,9): error FS0039: The value or constructor 'RestoreMSSolutionPackages' is not defined

What do I need to do resolve this issue on Mono? The build runs fine on Windows.

**Comment by forki** [comment]
I reproduced in https://travis-ci.org/fsharp/FAKE/builds/68119473

    Installing 'FAKE 3.4.1'. 

that's probably way to outdated. So please update your FAKE version in build.sh

**Comment by Aaronontheweb** [comment]
Thanks @forki !
