### ISSUE TITLE
Get started sample broken when updated to 5.12.1(Ubuntu 18.04)

### ISSUE THREAD

**Issue by humhei** [fsharp/FAKE#2261]
### Description

Get started sample broken when updated to 5.12.1

### Repro steps
1. Step A 
```fsharp
#r "paket:
nuget Fake.Core.Target = 5.12.1 //"
#load "./.fake/build.fsx/intellisense.fsx"

open Fake.Core

// Default target
Target.create "Default" (fun _ ->
  Trace.trace "Hello World from FAKE"
)

// start build
Target.runOrDefault "Default"
```

2. Step B

### Expected behavior

Script ran successfully
### Actual behavior

Script is not valid:
        /home/jia/Documents/vscode/Test/build.fsx (8,0)-(8,6): Error FS0039: The value, namespace, type or module 'Target' is not defined.
        /home/jia/Documents/vscode/Test/build.fsx (13,0)-(13,6): Error FS0039: The value, namespace, type or module 'Target' is not defined.

### Known workarounds

pin Fake.Core.Target to 5.12.0

### Related information 

* Operating system
* Ubuntu 18.04

**Comment by matthid** [comment]
The following worked for me:
```
docker run --name faketest --rm -ti microsoft/dotnet
mkdir /test && cd /test
# in another shell `docker cp .\build.fsx faketest:/test/build.fsx`
dotnet tool install -g fake-cli
export PATH="$PATH:/root/.dotnet/tools"
fake build
```

Can you try to give exact steps to reproduce (or send a zipped sample)?

By the way here is the output from the session:


```
PS C:\Users\matth> docker run --rm --name faketest -ti microsoft/dotnet
root@27ca9bec2721:/# mkdir /test && cd /test
root@27ca9bec2721:/test# dotnet tool install -g fake-cli
Tools directory '/root/.dotnet/tools' is not currently on the PATH environment variable.
If you are using bash, you can add it to your profile by running the following command:

cat << \EOF >> ~/.bash_profile
# Add .NET Core SDK tools
export PATH="$PATH:/root/.dotnet/tools"
EOF

You can add it to the current session by running the following command:

export PATH="$PATH:/root/.dotnet/tools"

You can invoke the tool using the following command: fake
Tool 'fake-cli' (version '5.12.1') was successfully installed.
root@27ca9bec2721:/test# export PATH="$PATH:/root/.dotnet/tools"
root@27ca9bec2721:/test# fake build
Updating group Main in /test/.fake/build.fsx/paket.dependencies
Resolving packages for group Main:
 - Fake.Core.Target is pinned to 5.12.1
 - Fake.Core.CommandLineParsing 5.12.1
 - Fake.Core.Context 5.12.1
 - Fake.Core.Environment 5.12.1
 - Fake.Core.FakeVar 5.12.1
 - Fake.Core.Process 5.12.1
 - Fake.Core.String 5.12.1
 - Fake.Core.Trace 5.12.1
 - FSharp.Core 4.6.2
 - System.Reactive.Compatibility 4.1.3
 - FSharp.Control.Reactive 4.1.0
 - Fake.IO.FileSystem 5.12.1
 - System.Diagnostics.Process 4.3.0
 - System.Reactive.Core 4.1.3
 - System.Reactive.Interfaces 4.1.3
 - System.Reactive.Linq 4.1.3
 - System.Reactive.PlatformServices 4.1.3
 - System.Reactive.Providers 4.1.3
 - FParsec 1.0.3
 - System.Threading.Tasks.Extensions 4.5.2
 - System.Diagnostics.FileVersionInfo 4.3.0
 - System.IO.FileSystem.Watcher 4.3.0
 - Microsoft.Win32.Primitives 4.3.0
 - Microsoft.Win32.Registry 4.5.0
 - runtime.native.System 4.3.1
 - System.Collections 4.3.0
 - System.Diagnostics.Debug 4.3.0
 - System.Globalization 4.3.0
 - System.IO 4.3.0
 - System.IO.FileSystem 4.3.0
 - System.IO.FileSystem.Primitives 4.3.0
 - System.Resources.ResourceManager 4.3.0
 - System.Runtime 4.3.1
 - System.Runtime.Extensions 4.3.1
 - System.Runtime.Handles 4.3.0
 - System.Runtime.InteropServices 4.3.0
 - System.Text.Encoding 4.3.0
 - System.Text.Encoding.Extensions 4.3.0
 - System.Threading 4.3.0
 - System.Threading.Tasks 4.3.0
 - System.Threading.Thread 4.3.0
 - System.Threading.ThreadPool 4.3.0
 - System.Reactive 4.1.3
 - NETStandard.Library 2.0.3
 - System.Runtime.CompilerServices.Unsafe 4.5.2
 - System.Memory 4.5.2
 - System.Security.AccessControl 4.5.0
 - System.Security.Principal.Windows 4.5.1
 - System.Buffers 4.5.0
Trial1 (NuGet.GetVersions) did not yield any results, trying again.
   https://api.nuget.org/v3-flatcontainer/system.threading.overlapped/index.json?semVerLevel=2.0.0
 - System.Threading.Overlapped 4.3.0
 - System.Runtime.InteropServices.WindowsRuntime 4.3.0
 - System.Reflection 4.3.0
 - System.Reflection.Primitives 4.3.0
 - System.Reflection.Metadata 1.6.0
 - Microsoft.NETCore.Targets 2.1.0
 - Microsoft.NETCore.Platforms 2.2.0
 - System.Numerics.Vectors 4.5.0
 - System.Collections.Immutable 1.5.0
Locked version resolution written to /test/.fake/build.fsx/paket.lock
Starting full restore process.
Downloading Microsoft.NETCore.Platforms 2.2
Downloading System.Runtime.InteropServices.WindowsRuntime 4.3
Downloading System.Globalization 4.3
Downloading Fake.Core.CommandLineParsing 5.12.1
Downloading System.Reactive.PlatformServices 4.1.3
Download of Microsoft.NETCore.Platforms 2.2 done in 593 milliseconds. (423 kbit/s, 0 MB)
Download of Fake.Core.CommandLineParsing 5.12.1 done in 620 milliseconds. (3812 kbit/s, 0 MB)
Downloading Fake.Core.Context 5.12.1
Downloading Microsoft.NETCore.Targets 2.1
Download of System.Reactive.PlatformServices 4.1.3 done in 663 milliseconds. (564 kbit/s, 0 MB)
Downloading System.Reactive.Providers 4.1.3
Download of System.Runtime.InteropServices.WindowsRuntime 4.3 done in 668 milliseconds. (1816 kbit/s, 0 MB)
Downloading System.Security.AccessControl 4.5
Download of System.Globalization 4.3 done in 745 milliseconds. (6326 kbit/s, 0 MB)
Downloading System.IO 4.3
Download of Fake.Core.Context 5.12.1 done in 609 milliseconds. (676 kbit/s, 0 MB)
Downloading Fake.Core.Environment 5.12.1
Download of System.Reactive.Providers 4.1.3 done in 586 milliseconds. (637 kbit/s, 0 MB)
Downloading System.Reflection 4.3
Download of Microsoft.NETCore.Targets 2.1 done in 619 milliseconds. (393 kbit/s, 0 MB)
Downloading Microsoft.Win32.Primitives 4.3
Download of System.Security.AccessControl 4.5 done in 719 milliseconds. (6140 kbit/s, 0 MB)
Downloading System.Security.Principal.Windows 4.5.1
Download of System.IO 4.3 done in 732 milliseconds. (7690 kbit/s, 0 MB)
Downloading System.IO.FileSystem 4.3
Download of System.Reflection 4.3 done in 664 milliseconds. (8456 kbit/s, 0 MB)
Download of Microsoft.Win32.Primitives 4.3 done in 672 milliseconds. (753 kbit/s, 0 MB)
Downloading Microsoft.Win32.Registry 4.5
Downloading System.Reflection.Metadata 1.6
Download of Fake.Core.Environment 5.12.1 done in 696 milliseconds. (923 kbit/s, 0 MB)
Downloading Fake.Core.FakeVar 5.12.1
Download of System.IO.FileSystem 4.3 done in 591 milliseconds. (3713 kbit/s, 0 MB)
Downloading System.IO.FileSystem.Primitives 4.3
Download of System.Security.Principal.Windows 4.5.1 done in 706 milliseconds. (4415 kbit/s, 0 MB)
Downloading System.Text.Encoding 4.3
Download of Fake.Core.FakeVar 5.12.1 done in 538 milliseconds. (508 kbit/s, 0 MB)
Downloading Fake.Core.Process 5.12.1
Download of Microsoft.Win32.Registry 4.5 done in 603 milliseconds. (4655 kbit/s, 0 MB)
Downloading NETStandard.Library 2.0.3
Download of System.IO.FileSystem.Primitives 4.3 done in 588 milliseconds. (1292 kbit/s, 0 MB)
Downloading System.IO.FileSystem.Watcher 4.3
Download of System.Reflection.Metadata 1.6 done in 786 milliseconds. (8672 kbit/s, 0 MB)
Downloading System.Reflection.Primitives 4.3
Download of System.Text.Encoding 4.3 done in 664 milliseconds. (3943 kbit/s, 0 MB)
Downloading System.Text.Encoding.Extensions 4.3
Download of Fake.Core.Process 5.12.1 done in 818 milliseconds. (3182 kbit/s, 0 MB)
Downloading Fake.Core.String 5.12.1
Download of System.IO.FileSystem.Watcher 4.3 done in 789 milliseconds. (1965 kbit/s, 0 MB)
Downloading System.Memory 4.5.2
Download of System.Reflection.Primitives 4.3 done in 810 milliseconds. (2782 kbit/s, 0 MB)
Downloading System.Resources.ResourceManager 4.3
Download of System.Text.Encoding.Extensions 4.3 done in 775 milliseconds. (2520 kbit/s, 0 MB)
Downloading System.Threading 4.3
Download of NETStandard.Library 2.0.3 done in 1 second. (20023 kbit/s, 3 MB)
Download of System.Memory 4.5.2 done in 313 milliseconds. (3939 kbit/s, 0 MB)
Downloading System.Numerics.Vectors 4.5
Downloading runtime.native.System 4.3.1
Download of Fake.Core.String 5.12.1 done in 754 milliseconds. (802 kbit/s, 0 MB)
Downloading Fake.Core.Target 5.12.1
Download of System.Resources.ResourceManager 4.3 done in 677 milliseconds. (1015 kbit/s, 0 MB)
Downloading System.Runtime 4.3.1
Download of System.Threading 4.3 done in 793 milliseconds. (7143 kbit/s, 0 MB)
Downloading System.Threading.Overlapped 4.3
Download of runtime.native.System 4.3.1 done in 585 milliseconds. (406 kbit/s, 0 MB)
Downloading System.Buffers 4.5
Download of System.Numerics.Vectors 4.5 done in 640 milliseconds. (4784 kbit/s, 0 MB)
Downloading System.Reactive 4.1.3
Download of Fake.Core.Target 5.12.1 done in 591 milliseconds. (1524 kbit/s, 0 MB)
Downloading Fake.Core.Trace 5.12.1
Download of System.Buffers 4.5 done in 659 milliseconds. (1288 kbit/s, 0 MB)
Downloading System.Collections 4.3
Download of System.Threading.Overlapped 4.3 done in 978 milliseconds. (1371 kbit/s, 0 MB)
Downloading System.Threading.Tasks 4.3
Download of System.Runtime 4.3.1 done in 2 seconds. (27706 kbit/s, 6 MB)
Download of Fake.Core.Trace 5.12.1 done in 1 second. (823 kbit/s, 0 MB)
Downloading Fake.IO.FileSystem 5.12.1
Downloading System.Runtime.CompilerServices.Unsafe 4.5.2
Download of System.Reactive 4.1.3 done in 2 seconds. (9310 kbit/s, 2 MB)
Downloading System.Reactive.Compatibility 4.1.3
Download of Fake.IO.FileSystem 5.12.1 done in 257 milliseconds. (6721 kbit/s, 0 MB)
Downloading FParsec 1.0.3
Download of System.Runtime.CompilerServices.Unsafe 4.5.2 done in 257 milliseconds. (3259 kbit/s, 0 MB)
Downloading System.Runtime.Extensions 4.3.1
Download of System.Collections 4.3 done in 1 second. (3493 kbit/s, 0 MB)
Downloading System.Collections.Immutable 1.5
Download of System.Threading.Tasks 4.3 done in 1 second. (3855 kbit/s, 0 MB)
Downloading System.Threading.Tasks.Extensions 4.5.2
Download of System.Reactive.Compatibility 4.1.3 done in 582 milliseconds. (286 kbit/s, 0 MB)
Downloading System.Reactive.Core 4.1.3
Download of FParsec 1.0.3 done in 655 milliseconds. (5213 kbit/s, 0 MB)
Downloading FSharp.Control.Reactive 4.1
Download of System.Runtime.Extensions 4.3.1 done in 759 milliseconds. (11272 kbit/s, 1 MB)
Downloading System.Runtime.Handles 4.3
Download of FSharp.Control.Reactive 4.1 done in 337 milliseconds. (4752 kbit/s, 0 MB)
Downloading FSharp.Core 4.6.2
Download of System.Collections.Immutable 1.5 done in 776 milliseconds. (8292 kbit/s, 0 MB)
Downloading System.Diagnostics.Debug 4.3
Download of System.Threading.Tasks.Extensions 4.5.2 done in 621 milliseconds. (1124 kbit/s, 0 MB)
Download of System.Reactive.Core 4.1.3 done in 590 milliseconds. (651 kbit/s, 0 MB)
Downloading System.Reactive.Interfaces 4.1.3
Downloading System.Threading.Thread 4.3
Download of System.Threading.Thread 4.3 done in 676 milliseconds. (1170 kbit/s, 0 MB)
Download of System.Reactive.Interfaces 4.1.3 done in 683 milliseconds. (550 kbit/s, 0 MB)
Downloading System.Reactive.Linq 4.1.3
Downloading System.Threading.ThreadPool 4.3
Download of System.Runtime.Handles 4.3 done in 950 milliseconds. (461 kbit/s, 0 MB)
Download of FSharp.Core 4.6.2 done in 797 milliseconds. (28304 kbit/s, 2 MB)
Download of System.Diagnostics.Debug 4.3 done in 721 milliseconds. (1661 kbit/s, 0 MB)
Downloading System.Runtime.InteropServices 4.3
Downloading System.Diagnostics.FileVersionInfo 4.3
Download of System.Reactive.Linq 4.1.3 done in 589 milliseconds. (642 kbit/s, 0 MB)
Download of System.Diagnostics.FileVersionInfo 4.3 done in 611 milliseconds. (1817 kbit/s, 0 MB)
Download of System.Threading.ThreadPool 4.3 done in 658 milliseconds. (1093 kbit/s, 0 MB)
Downloading System.Diagnostics.Process 4.3
Download of System.Runtime.InteropServices 4.3 done in 1 second. (20229 kbit/s, 2 MB)
Download of System.Diagnostics.Process 4.3 done in 687 milliseconds. (6332 kbit/s, 0 MB)
run Default
Building project with version: LocalBuild
Shortened DependencyGraph for Target Default:
<== Default

The running order is:
Group - 1
  - Default
Starting target 'Default'
Hello World from FAKE
Finished (Success) 'Default' in 00:00:00.0039352

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Default    00:00:00.0001652
Total:     00:00:00.0650448
Status:    Ok
---------------------------------------------------------------------
Performance:
 - Cli parsing: 274 milliseconds
 - Packages: 46 seconds
   - Resolver: 36 seconds (1 runs)
      - Runtime: 207 milliseconds
      - Blocked (retrieving package details): 11 seconds (33 times)
      - Blocked (retrieving package versions): 24 seconds (6 times)
      - Not Blocked (retrieving package details): 25 times
      - Not Blocked (retrieving package versions): 52 times
   - Disk IO: 769 milliseconds
   - Average Download Time: 169 milliseconds
   - Number of downloads: 58
   - Average Request Time: 305 milliseconds
   - Number of Requests: 118
   - Creating Runtime Graph: 37 milliseconds
   - Retrieve Assembly List: 329 milliseconds
 - Script compiling: 2 seconds
 - Script analyzing: 156 milliseconds
 - Script running: 220 milliseconds
 - Script cleanup: 0 milliseconds
 - Runtime: 50 seconds
```

**Comment by humhei** [comment]
![image](https://user-images.githubusercontent.com/25994449/53469179-f405bc00-3a97-11e9-973d-08a22ff088de.png)

I originally think this is beacuse of `FSharp.Core`  was updated to `4.6` in 5.12.1

Finnally get that this is because my cache file is not clear,

I don't know why it only exits a pdb file...

After delete this folder,

It worked again

**Comment by matthid** [comment]
Thanks for finding the root cause. Reported to paket: https://github.com/fsprojects/Paket/issues/3517
