### ISSUE TITLE
"error FS0193: internal error:  Value cannot be null.  Parameter name: con"

### ISSUE THREAD

**Issue by bentayloruk** [fsharp/FAKE#113]
_I wasn't sure whether to add this as a comment to #20.  Figured new issue would be best._

I'm getting "error FS0193: internal error:  Value cannot be null.  Parameter name: con" when running the simple build script below.  This script works with FAKE 1.64.7 but fails with the error on the latest  -pre version FAKE.2.1.155-alpha.

Any suggestions you might have on how to resolve/diagnose this would be great.  If you need more information, please tell me what you need.  Thanks.  

```
#I @".\src\packages\FAKE.2.1.155-alpha\tools"
#r @".\src\packages\FAKE.2.1.155-alpha\tools\FakeLib.dll"
open System
open Fake

let version = "0.1.0"
let buildOutputPath = @".\build\output"
let buildDirs = [ buildOutputPath; ]

let projFiles =
    !+ @".\src\**\*.csproj"
    -- @".\src\**\*Tests.csproj"
    |> Scan

Target "Clean" (fun _ -> CleanDirs buildDirs)

//Build
Target "BuildProjects" (fun _ ->
    MSBuild buildOutputPath "Build" ["Configuration", "Release"]  projFiles
    |> Log "BuildOutput:"
)


"Clean"
    ==> "BuildProjects" 

Run "BuildProjects" 
```
