### ISSUE TITLE
framework version mismatch between FAKE and Nuget packages

### ISSUE THREAD

**Issue by iwinux** [fsharp/FAKE#2588]
### Description

The `paket.dependencies` under the `.fake/<script>.fsx/` directory specifies `framework: netstandard2.0` but some packages (e.g.: [SchlenkR.FsHttp](https://www.nuget.org/packages/SchlenkR.FsHttp)) only work on `framework: netstandard2.1` and above.

### Repro steps

1. Create a script named `foo.fsx`:
    ```fsharp
    #r "paket: nuget SchlenkR.FsHttp"
    open FsHttp
    FsHttp.Fsi.Init.init()
    ```

2. Run the script with `fake run foo.fsx`.

### Expected behavior

It should have executed `foo.fsx` without errors.

### Actual behavior

It fails with output:

```
Updating group Main in .fake/foo.fsx/paket.dependencies
Resolving packages for group Main:
 - SchlenkR.FsHttp 5.1.0
Locked version resolution written to .fake/foo.fsx/paket.lock
Extracted Paket.Restore.targets to: .fake/foo.fsx/.paket/Paket.Restore.targets (Can be disabled with PAKET_SKIP_RESTORE_TARGETS=true)
Starting full restore process.
 Script is not valid:
        foo.fsx (2,5)-(2,11): Error FS0039: The namespace or module 'FsHttp' is not defined. Maybe you want one of the following:
           FSharp
        foo.fsx (3,0)-(3,6): Error FS0039: The value, namespace, type or module 'FsHttp' is not defined. Maybe you want one of the following:
           fst
           FSharp          
Hint: If you have updated your dependencies you might need to run 'paket install' or delete 'foo.fsx.lock' for fake to pick them up.
Hint: If this doesn't help but you are sure this should work try to clean your nuget cache and delete the .fake directory. If this helps please report this problem to Paket.
```

The content of `.fake/foo.fsx/paket.lock`:

```
STORAGE: NONE
RESTRICTION: == netstandard2.0
NUGET
  remote: https://api.nuget.org/v3/index.json
    SchlenkR.FsHttp (5.1)
```

### Related information 

* Operating system: macOS 10.15.7
* Branch:
* .NET Runtime, CoreCLR or Mono Version: .NET SDK 5.0.201
* Version of FAKE: 5.20.4

**Comment by baronfel** [comment]
FAKE pins its execution target framework to `netstandard2.0`, so bumping that (personally at this point I think it should be `net5.0` to align with `dotnet fsi`) would be a bit of work.

**Comment by iwinux** [comment]
@baronfel any guidance on how would that be done?

**Comment by matthid** [comment]
Note this is not just a simple version update. The main problem is compiling, we need reference assemblies of the framework to do this properly. While we could use runtime assemblies for this, that is not an officially supported scenario and I would urge to not go down that route again (like we did in previous fake versions). In netstandard20 those reference assemblies are available via NuGet and we transparently download them for compilation. That changed however, so we need to figure out how we can get the correct reference assemblies when we want to switch the framework.
At the time I hoped that it would just stay the way it was with updated packages...

One solution would be to depend on an installed SDK, and take the files from there. However, I don't really like that dependency for the runner... 

Another solution would be to just bundle them...

If anyone has an idea please let us know.

**Comment by iwinux** [comment]
For personal use, could I just build FAKE from source with latest SDK to work around the problem?

**Comment by matthid** [comment]
No, it's not about compiling FAKE, but about FAKE compiling the build script at runtime.

**Comment by seanamosw** [comment]
I was toying with running FAKE build scripts using `dotnet fsi` the other day, while it was for a different use case it could actually work for this.

The general idea was to run `paket generate-load-scripts`, then use `#load <path to generated group scripts loader.fsx>` in your build.fsx file instead of `#r paket: ...`.

Then you need to create and set a **fake** FAKE execution context, passing in the CLI args, in your build.fsx.
You can then run your build.fsx using `dotnet fsi build.fsx`.

I don't have code examples right now, I'll dig them up for you.

**Comment by seanamosw** [comment]
You can do this:

```
// paket.dependencies
group fake
    storage: none
    framework: net5.0
    source https://api.nuget.org/v3/index.json
    nuget Fake.Core.Target ~> 5
    nuget Fake.DotNet.Cli ~> 5
    nuget Fake.DotNet.Paket ~> 5
    nuget Fake.IO.FileSystem ~> 5
    nuget Fake.IO.Zip ~> 5
    nuget Fake.Tools.Git ~> 5
    nuget Fake.Tools.GitVersion ~> 5
    nuget FSharp.Core ~> 4
```
You can do this in your `build.sh/build.cmd`
```
dotnet paket generate-load-scripts --group fake -f net5.0
```

```
// build.fsx
#load ".paket/load/net50/fake/fake.group.fsx"

open Fake
open Fake.Core

let args = fsi.CommandLineArgs |> List.ofArray |> List.skip 1 // first arg will be "build.fsx"
let execContext = Context.FakeExecutionContext.Create false "build.fsx" args
Context.setExecutionContext (Context.RuntimeContext.Fake execContext)

Target.create "hello" <| fun _ ->
    printfn "Hello!"

Target.runOrDefaultWithArguments "Hello"
```
What this is basically doing is bypassing FAKE's compilation and using dotnet fsi to do it.

**Comment by matthid** [comment]
@seanamosw Sure, an even "easier" way is to just create a project, add the dependencies rename the `.fsx` to `.fs` add a main entry point and run `dotnet run`. Both require an installed .NET SDK.
