### ISSUE TITLE
CACHING ERROR building fszmq

### ISSUE THREAD

**Issue by Danl2620** [fsharp/FAKE#1639]
### Description

I clone fszmq (from `https://github.com/zeromq/fszmq`) and ran the build script (`./build.sh`) in the directory. The script errored out with the output shown below.

### Repro steps

Clone and `./build.sh`.

### Expected behavior

I expected the build to complete without errors.

### Actual behavior

Build did not complete. Errored out with this:

```
✔ danl@Dans-iMac 11:59 [~/proj/fszmq] $ ./build.sh
No version specified. Downloading latest stable.
Paket.exe 5.90.1.0 is up to date.
Paket version 5.90.1
Performance:
 - Disk IO: 695 milliseconds
 - Runtime: 1 second
FsiEvaluationException:

Error: 
	
	error FS0193: Specified method is not supported.
	

Output: [Loading /Users/danl/proj/fszmq/build.fsx]
	

Input: /Users/danl/proj/fszmq/build.fsx
\Arguments: 
  C:\fsi.exe
  --define:MONO

Exception: Yaaf.FSharp.Scripting.FsiEvaluationException: Error while compiling or executing fsharp snippet. ---> System.Exception: Operation failed. The error text has been print the error stream. To return the corresponding FSharpErrorInfo use the EvalInteractionNonThrowing, EvalScriptNonThrowing or EvalExpressionNonThrowing
  at Microsoft.FSharp.Compiler.Interactive.Shell+FsiEvaluationSession.commitResult[a,b] (Microsoft.FSharp.Core.FSharpChoice`2[T1,T2] res) [0x00030] in <5707a2f5ddab8ea7a7450383f5a20757>:0 
  at Microsoft.FSharp.Compiler.Interactive.Shell+FsiEvaluationSession.EvalScript (System.String filePath) [0x00014] in <5707a2f5ddab8ea7a7450383f5a20757>:0 
  at Yaaf.FSharp.Scripting.Helper+evalScript@1303.Invoke (System.String arg00) [0x00001] in <58c6891eccf1c534a74503831e89c658>:0 
  at Yaaf.FSharp.Scripting.Helper+saveScript@1295-1[a].Invoke (System.String path) [0x00033] in <58c6891eccf1c534a74503831e89c658>:0 
  at Yaaf.FSharp.Scripting.Helper+save_@1276-2[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00001] in <58c6891eccf1c534a74503831e89c658>:0 
  at Yaaf.FSharp.Scripting.Helper.consoleCapture[a] (System.IO.TextWriter out, System.IO.TextWriter err, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] f) [0x0001a] in <58c6891eccf1c534a74503831e89c658>:0 
  at Yaaf.FSharp.Scripting.Helper.redirectOut@1247[a] (System.Boolean preventStdOut, Yaaf.FSharp.Scripting.Helper+OutStreamHelper out, Yaaf.FSharp.Scripting.Helper+OutStreamHelper err, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] f) [0x0006d] in <58c6891eccf1c534a74503831e89c658>:0 
  at Yaaf.FSharp.Scripting.Helper+save_@1275-1[a].Invoke (System.String text) [0x0002c] in <58c6891eccf1c534a74503831e89c658>:0 
   --- End of inner exception stack trace ---
  at Yaaf.FSharp.Scripting.Helper+save_@1275-1[a].Invoke (System.String text) [0x0009e] in <58c6891eccf1c534a74503831e89c658>:0 
  at Yaaf.FSharp.Scripting.Helper+session@1306.Yaaf-FSharp-Scripting-IFsiSession-EvalScriptWithOutput (System.String ) [0x00001] in <58c6891eccf1c534a74503831e89c658>:0 
  at Fake.FSIHelper.runScriptUncached (System.Boolean useCache, System.String scriptPath, System.Collections.Generic.IEnumerable`1[T] fsiOptions, System.Boolean printDetails, Fake.FSIHelper+CacheInfo cacheInfo, System.IO.TextWriter out, System.IO.TextWriter err) [0x0019a] in <58c6891eccf1c534a74503831e89c658>:0 
error FS0193: Specified method is not supported.

CACHING ERROR - please open a issue on FAKE and /cc @matthid

Error: System.NotSupportedException: Type 'FSI_0005.Build' was not completed.
  at System.Reflection.Emit.ModuleBuilder.Save () [0x00048] in <6121bbff18d447c19175abd75faed747>:0 
  at System.Reflection.Emit.AssemblyBuilder.Save (System.String assemblyFileName, System.Reflection.PortableExecutableKinds portableExecutableKind, System.Reflection.ImageFileMachine imageFileMachine) [0x0022b] in <6121bbff18d447c19175abd75faed747>:0 
  at System.Reflection.Emit.AssemblyBuilder.Save (System.String assemblyFileName) [0x00000] in <6121bbff18d447c19175abd75faed747>:0 
  at Fake.FSIHelper.handleCaching[a] (System.Boolean printDetails, Yaaf.FSharp.Scripting.IFsiSession session, a fsiErrorOutput, System.IO.DirectoryInfo cacheDir, Fake.FSIHelper+CacheInfo cacheInfo) [0x00046] in <58c6891eccf1c534a74503831e89c658>:0 
✘ danl@Dans-iMac 12:00 [~/proj/fszmq] $ 

```

### Known workarounds

Unknown.

### Related information 

* Operating system: macOS Sierra 10.12.6
* Branch: main
* .NET Runtime, CoreCLR or Mono Version: Mono 5.0.1.1 (2017-02/5077205)
* Performance information, links to performance testing scripts

/cc @matthid

**Comment by matthid** [comment]
Interesting. Are you able to try a different mono version? This is likely a mono bug or maybe a FCS bug. If I find the time I might be able to release a FAKE 4 with updated FCS (but I have difficulties releasing FAKE 4)

**Comment by auduchinok** [comment]
@matthid I'm having the same issue on FSharp.Extras repo with its current master and Mono 5.0.1.1. The call stack is identical to the one @Danl2620 submitted.

**Comment by auduchinok** [comment]
@matthid Using Mono 4.8 I was able to build projects and run tests:
```
eugene@unit-937:FSharpx.Extras [master]$ export PATH=/Library/Frameworks/Mono.framework/Versions/4.8.0/bin:$PATH
eugene@unit-937:FSharpx.Extras [master]$ mono --version
Mono JIT compiler version 4.8.0 (mono-4.8.0-branch/8f6d0f6 Thu Mar  9 11:59:17 EST 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/8b1520c)
	GC:            sgen
eugene@unit-937:FSharpx.Extras [master]$ ./build.sh 
Checking Paket version (downloading latest stable)...
Paket.exe 5.96.1 is up to date.
Paket version 5.96.1
Last restore is still up to date.
Performance:
 - Runtime: 843 milliseconds
Building project with version: LocalBuild
Shortened DependencyGraph for Target All:
<== All
   <== BuildPackage
      <== NuGet
         <== GenerateDocs
            <== GenerateReferenceDocs
               <== RunTests
                  <== CopyBinaries
                     <== Build
                        <== AssemblyInfo
               <== GenerateHelp

The resulting target order is:
 - AssemblyInfo
 - Build
 - CopyBinaries
 - RunTests
 - GenerateHelp
 - GenerateReferenceDocs
 - GenerateDocs
 - NuGet
 - BuildPackage
 - All
Starting Target: AssemblyInfo 
Created AssemblyInfo file "/Users/eugene/Developer/FSharpx.Extras/src/FSharpx.Extras/AssemblyInfo.fs".
Created AssemblyInfo file "/Users/eugene/Developer/FSharpx.Extras/src/FSharpx.Text.StructuredFormat/AssemblyInfo.fs".
Finished Target: AssemblyInfo
Starting Target: Build (==> AssemblyInfo)
Building project: /Users/eugene/Developer/FSharpx.Extras/FSharpx.Extras.sln
  xbuild  /Users/eugene/Developer/FSharpx.Extras/FSharpx.Extras.sln /t:Build    /p:RestorePackages="False" /p:Configuration="Release" /p:DefineConstants="MONO" /logger:Fake.MsBuildLogger+ErrorLogger,"/Users/eugene/Developer/FSharpx.Extras/packages/build/FAKE/tools/FakeLib.dll"
XBuild Engine Version 14.0
Mono, Version 4.8.0.0
Copyright (C) 2005-2013 Various Mono authors

Build started 9/13/2017 7:05:13 PM.
...
```
However on generating help stage it failed while calling the latest Mono probably by an explicit path. The exception stack trace is the same.
```
Building documentation (Default), this could take some time, please wait...
/Library/Frameworks/Mono.framework/Commands/mono  "/Users/eugene/Developer/FSharpx.Extras/packages/build/FAKE/tools/FAKE.exe"  --fsiargs -d:FAKE --define:RELEASE --define:HELP "generate.fsx"
FsiEvaluationException:

Error: 
	
	error FS0193: Specified method is not supported.
	

Output: [Loading /Users/eugene/Developer/FSharpx.Extras/packages/build/FSharp.Formatting/FSharp.Formatting.fsx
	 Loading /Users/eugene/Developer/FSharpx.Extras/docs/tools/generate.fsx]
	

Input: /Users/eugene/Developer/FSharpx.Extras/docs/tools/generate.fsx
\Arguments: 
  C:\fsi.exe
  --define:FAKE
  --define:RELEASE
  --define:HELP

```

**Comment by matthid** [comment]
Yes it looks like a mono bug

**Comment by auduchinok** [comment]
I've also tried using 5.2.0.215. With this version build and tests work fine, but help generation fails in the same way, although working on 5.2 as well.
```
eugene@unit-937:FSharpx.Extras [master ?]$ /Library/Frameworks/Mono.framework/Commands/mono --version
Mono JIT compiler version 5.2.0.215 (d15-3/da80840 Thu Jul 20 16:43:07 EDT 2017)
```

**Comment by DmitryBatalov** [comment]
@matthid and @auduchinok I've tried to build FSharp.Data on mono v. 5.2.0.215 and got the error described in issue. OS: Ubuntu 16.04.3 LTS

**Comment by matthid** [comment]
I guess you all are actually using latest stable FAKE release?

**Comment by matthid** [comment]
Closing due to inactivity.
